{% set name = "kedro-telemetry" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3765faf5cb3e5ff7e868d89f47eeab19d2055bf561cec3d82730649cd32cabb0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - kedro >=0.18.0,<0.19.0
    - requests >=2.20,<3.0

test:
  imports:
    - kedro_telemetry
  commands:
    - pip check
  requires:
    - pip

about:
  summary: To find out how Kedro's features are used, the Kedro team have created an opt-in Kedro-Telemetry plugin to gather anonymised (before being sent across the internet) and aggregated usage analytics.
  home: https://github.com/kedro-org/kedro-plugins/tree/main/kedro-telemetry
  license: Apache-2.0
  license_file: LICENSE.md
  dev_url: https://github.com/kedro-org/kedro-plugins/tree/main/kedro-telemetry

extra:
  recipe-maintainers:
    - zaigner
