{% set name = "kedro-telemetry" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kedro_telemetry-{{ version }}.tar.gz
  sha256: 4a885b6c5e0e060213933b59290c8ef00266d8e5d3a1e627fbee3d3531953e67

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - kedro >=0.18.0
    - requests >=2.20,<3.0
    - appdirs >=1.4.4

test:
  imports:
    - kedro_telemetry
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Kedro-Telemetry is a plugin that gathers anonymised and aggregated usage analytics to help the Kedro team understand how Kedro is used and prioritise improvements to the product accordingly.
  home: https://github.com/kedro-org/kedro-plugins/tree/main/kedro-telemetry
  license: Apache-2.0
  license_file: LICENSE.md
  dev_url: https://github.com/kedro-org/kedro-plugins/tree/main/kedro-telemetry

extra:
  recipe-maintainers:
    - rxm7706
    - zaigner
