{% set name = "kedro-telemetry" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kedro_telemetry-{{ version }}.tar.gz
  sha256: d46f9b277ad5f38a741752da039a0c96ebbbb00057a739a792cfbc6adc0e44a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - kedro >=0.18.0
    - requests >=2.20,<3.0
    - appdirs >=1.4.4
    - tomli-w

test:
  imports:
    - kedro_telemetry
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Kedro-Telemetry is a plugin that gathers anonymised and aggregated usage analytics to help the Kedro team understand how Kedro is used and prioritise improvements to the product accordingly.
  home: https://github.com/kedro-org/kedro-plugins/tree/main/kedro-telemetry
  license: Apache-2.0
  license_file: LICENSE.md
  dev_url: https://github.com/kedro-org/kedro-plugins/tree/main/kedro-telemetry

extra:
  recipe-maintainers:
    - rxm7706
    - zaigner
