schema_version: 1

context:
  name: kedro-telemetry
  version: 0.6.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/kedro_telemetry-${{ version }}.tar.gz
  sha256: 0fe452af6eac2723da7fd1d62cb1551db3e78ccd7b7e16539af440db545c47bf

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - kedro >=0.18.0
    - requests >=2.20,<3.0
    - appdirs >=1.4.4
    - tomli-w

tests:
  - python:
      imports:
        - kedro_telemetry
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Kedro-Telemetry is a plugin that gathers anonymised and aggregated usage analytics to help the Kedro team understand how Kedro is used and prioritise improvements to the product accordingly.
  license: Apache-2.0
  license_file: LICENSE.md
  homepage: https://github.com/kedro-org/kedro-plugins/tree/main/kedro-telemetry
  repository: https://github.com/kedro-org/kedro-plugins/tree/main/kedro-telemetry

extra:
  recipe-maintainers:
    - rxm7706
    - zaigner
